layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  github: walidkhb
  website: https://www.wbadawi.com

topics:
  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/5b3600551580494ff6f0505b531a5e0e738eee28/topics/java/java.png

  - name: Spring Boot
    web_url: https://github.com/topics/spring-boot
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/spring-boot/spring-boot.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png

  - name: Angular
    web_url: https://github.com/topics/angular
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/angular/angular.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: API Design
    web_url: https://github.com/topics/api

  - name: Enterprise Integration
    web_url: https://github.com/topics/enterprise

  - name: BPM
    web_url: https://github.com/topics/bpm